name: Build Flet APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# เพิ่มส่วนนี้เพื่อบอก GitHub ให้ใช้ Node.js 24 ตามที่เขาแนะนำ
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet
        run: |
          pip install flet

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          flet build apk my_project/main.py --android-permissions INTERNET
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: build/apk/*.apk
          if-no-files-found: error
